const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/touch-gesture-regression.json'), 'utf8'));

assert.equal(fixture.dragThresholdPx, 6);
assert.equal(fixture.pinDragThresholdPx, 5);
assert.ok(fixture.ballClickSuppressionMs > fixture.pinClickSuppressionMs);

// Scrolling remains available on the chart, while draggable controls take
// ownership only after a meaningful movement threshold is crossed.
assert.match(source, /\.chartArea\.chart\{[\s\S]*?touch-action:pan-x/);
assert.match(source, /\.ballListButton\{touch-action:none\}/);
assert.match(source, /function ballPointerMove\(event\)[\s\S]*?Math\.hypot\(event\.clientX-drag\.startX,event\.clientY-drag\.startY\)>6/);
assert.match(source, /function ballPointerEnd\(event\)[\s\S]*?ballSuppressClickUntil=Date\.now\(\)\+450[\s\S]*?ballPointerDrag=null/);

// Pin drags must cancel cleanly and suppress the synthetic click generated by
// touch browsers after a drag; a simple tap remains a normal selection.
assert.match(source, /function pinDragMove\(event\)[\s\S]*?Math\.hypot\(event\.clientX-drag\.startX,event\.clientY-drag\.startY\)>5/);
assert.match(source, /function pinDragEnd\(event\)[\s\S]*?pinSuppressClickUntil=Date\.now\(\)\+350/);
assert.match(source, /setAttribute\('onpointercancel','pinDragEnd\(event\)'\)/);
assert.match(source, /function pinTap\(event,pin\)[\s\S]*?Date\.now\(\)<pinSuppressClickUntil[\s\S]*?event\.stopPropagation\(\)/);
assert.match(source, /onpointercancel="ballPointerEnd\(event\)"/);

console.log('Touch gesture checks passed for scroll/drag separation, pointer cancellation, repeated taps, and click suppression.');
